### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 715670119** [gedoor/MyBookshelf#1]
自己配置书源太过复杂，即使有视频教程也有相当的难度，很难对号入座，建议当用户手动输入目标网址的时候，内部程序能自动触发进入该网址，进行自动抓取必须的规则，且自行填写，个人认为，程序员做出可以抓取网站某些规则的程序的难度远小于小白自己抓取吧……

**Comment by M17764017422** [comment]
想法是好的，但非常不好实现
