### ISSUE TITLE
请问能否增加目录倒叙的功能

### ISSUE THREAD

**Issue by wjm2038** [gedoor/MyBookshelf#104]
有些网站的目录显示为倒叙显示，导致在软件里写好规则之后是从最新的章节到最旧的章节。希望可以在规则里添加一个倒叙目录的变量。多谢

**Comment by gedoor** [comment]
目录规则前加负号, -

**Comment by wjm2038** [comment]
多谢！@gedoor

**Comment by gedoor** [comment]
不需要啊,有快速滚动条

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: jm wang <notifications@github.com>
发送时间: Wednesday, October 31, 2018 8:02:07 PM
收件人: gedoor/MyBookshelf
抄送: kunfei; Mention
主题: Re: [gedoor/MyBookshelf] 请问能否增加目录倒叙的功能 (#104)


Closed #104<https://github.com/gedoor/MyBookshelf/issues/104>.

―
