### ISSUE TITLE
英文系统下，中文epub全部乱码，txt正常

### ISSUE THREAD

**Issue by herexf** [gedoor/MyBookshelf#108]
英文系统下，中文epub全部乱码，txt正常
尝试过使用本地自定义中文字体，也不行。。
![tim 20181104015541](https://user-images.githubusercontent.com/33848303/47953696-40068f80-dfd5-11e8-8718-afc4a61ef365.jpg)

**Comment by gedoor** [comment]
最新版本加入了编码设置

**Comment by herexf** [comment]
多谢，设置为UTF-8一切正常，
理论这个应该是默认编码吗？哈哈

**Comment by herexf** [comment]
新的问题

设置编码可以解决内容乱码，但是目录还是乱码，没找到刷新目录的地方。

**可以改成设置编码自动刷新一次目录不?**

谢谢

**Comment by gedoor** [comment]
下次更新解决

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: herexf <notifications@github.com>
发送时间: Monday, November 5, 2018 12:10:34 PM
收件人: gedoor/MyBookshelf
抄送: kunfei; State change
主题: Re: [gedoor/MyBookshelf] 英文系统下，中文epub全部乱码，txt正常 (#108)


新的问题

设置编码可以解决内容乱码，但是目录还是乱码，没找到刷新目录的地方。

可以改成设置编码自动刷新一次目录不?

谢谢

―
