### ISSUE TITLE
[bug]下載更新包時卡頓崩潰

### ISSUE THREAD

**Issue by ThomasHawaiiKing** [gedoor/MyBookshelf#109]
描述：軟件下載更新包時，手機桌面啓動器和鎖屏界面下拉通知快捷開關非常卡頓，並導致崩潰重啓桌面啓動器，最近兩次更新都是如此（我也只更新過這兩次）。
手機：Google Nexus 5
系統：官方最終版（6.0.1）未root
啓動器：Lawnchair

**Comment by gedoor** [comment]
到市场更新吧,
