### ISSUE TITLE
[建议]某些网站，在搜索结果只有一个时不出现列表页直接跳转到书籍页，从而导致搜索结果解析失败的问题，是否可以通过拒绝跳转解决？

### ISSUE THREAD

**Issue by qiantangit** [gedoor/MyBookshelf#11]
标题虽长，但意思应该没错。。

是不是可以多加个判断，返回值如果是301/302， 就拒绝跳转，从 html.headers[‘Location’] 获取书籍页URL。

不懂JAVA，大神可以瞧瞧网上这段儿Python代码 :)

https://blog.csdn.net/Mao_code/article/details/54017708

```
...
 html = requests.get(url, headers=headers, allow_redirects=False)
    return html.headers['Location']
```

> allow_redirects=False的意义为拒绝默认的301/302重定向从而可以通过html.headers[‘Location’]拿到重定向的URL。

**Comment by gedoor** [comment]
可以通过多规则获取
