### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by qiuyue2379** [gedoor/MyBookshelf#110]

**Comment by qiuyue2379** [comment]
内容页 closec

**Comment by gedoor** [comment]
应该是书源问题吧

**Comment by gedoor** [comment]
换个源试试,我手机上没有问题啊

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: qiuyue2379 <notifications@github.com>
发送时间: Sunday, November 11, 2018 8:24:29 PM
收件人: gedoor/MyBookshelf
抄送: kunfei; State change
主题: Re: [gedoor/MyBookshelf] 加载失败 (#110)


2018/11/3 以前是好的，就是你（增加EPUB文件支持）后就不行。

―

**Comment by qiuyue2379** [comment]
我用的是我自己的源，用别的源是好的，可是我在以前是好的呀
搜索列表是好的，就是内容页出现错误！
http://qiuyue.vicp.net:85/8/8400/6637128.html。
