### ISSUE TITLE
勾选隐藏状态栏选项出现的问题

### ISSUE THREAD

**Issue by lvnoey** [gedoor/MyBookshelf#112]
勾选隐藏状态栏选项之后 点屏幕中间弹出菜单或者切换菜单会触发换源(内容替换？),  四五个版本前大更新的时候出现的吧, 最新版还在触发不过更快了 只能看到文字变动
 2.0.4.10810没问题, 这里不应该出现替换内容吧, 能不能去掉这个触发

**Comment by gedoor** [comment]
会触发,只是原来没有显示,隐藏状态栏,显示区域大小会变化,需要重新计算每页文字.
