### ISSUE TITLE
希望可以增强净化功能

### ISSUE THREAD

**Issue by anye1998** [gedoor/MyBookshelf#121]
希望净化不只是支持正则表达式，还可以支持普通的直接去除的那种，就像我在图中展示的那样，能够大大减少学习成本。

![screenshot_2018-11-20-18-31-06-134_com lucenly pocketbook](https://user-images.githubusercontent.com/43033792/48768907-4dba5580-ecf5-11e8-9ca3-9856701108c7.png)
![screenshot_2018-11-20-18-31-11-808_com lucenly pocketbook](https://user-images.githubusercontent.com/43033792/48768914-4f841900-ecf5-11e8-829f-ec8f70c79fdf.png)
![screenshot_2018-11-20-18-31-18-558_com lucenly pocketbook](https://user-images.githubusercontent.com/43033792/48768919-514ddc80-ecf5-11e8-8605-94994c4b54f4.png)

**Comment by atbest** [comment]
早就支持了
