### ISSUE TITLE
不能打开书籍看书！

### ISSUE THREAD

**Issue by xukongyang** [gedoor/MyBookshelf#124]
昨天在boox电子书nova（安卓版本6.01）上安装会提示书源为空，然后确认导入书源后是没有导入书源的，只有从其他手机的备份恢复后才会出现书源，然后运行时偶尔会出错，但是书是能看的。

今天我删掉app重新安装，从其他手机的备份只倒入书源，其他设置保持安装后的初始状态，能搜索到书，但是点击书目想要看书就一直报错，然后程序停止。

报错信息如下：

![e2bbde4c-1253-4e58-9a1f-de293b28cdf7](https://user-images.githubusercontent.com/4610225/49197818-5680ea80-f3cb-11e8-82a5-98081be4a498.png)

**Comment by gedoor** [comment]
缓存目录下的错误报告发出来看看

**Comment by gedoor** [comment]
把

apply plugin: 'io.fabric'

apply plugin: 'com.google.gms.google-services'
这两行删除就好了,这是收集错误报告和使用量用的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: xukongyang <notifications@github.com>
发送时间: Thursday, November 29, 2018 3:28:03 PM
收件人: gedoor/MyBookshelf
抄送: kunfei; Comment
主题: Re: [gedoor/MyBookshelf] 不能打开书籍看书！ (#124)


首先谢谢gedoor的回复，

不过我经过查看源代码，找到原因了，查看日志，发现出错的代码是

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
at com.monke.monkeybook.view.activity.ReadBookActivity.t(ReadBookActivity.java:265)
at com.monke.monkeybook.view.activity.ReadBookActivity.k(ReadBookActivity.java:226)
at com.monke.monkeybook.base.MBaseActivity.onCreate(MBaseActivity.java:40)
at com.monke.monkeybook.view.activity.ReadBookActivity.onCreate(ReadBookActivity.java:143)

看描述是屏幕的时间相关设置导致的。

我想了半天，应该是因为我在系统设置中把自动休眠设置为「永不」的原因（因为我要下载书籍，要下很多本书，屏幕自动休眠就会中断下载书籍，所以我就把自动休眠设置为了「永不」）

果然，我把超时时间设置为一个值，例如15分钟，再重新打开阅读，就能正常打开书籍了！！！

另外请教一下gedoor，我尝试编译源码，但是提示 File google-services.json is missing. The Google Services Plugin cannot function without it. 这个该怎么破啊？可以私信我一个这个文件吗？

―

**Comment by xukongyang** [comment]
谢谢答复，注释掉上面2行后，编译不报错了，但是在 build apk的时候又报了个错：

Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningDebug'.
> Keystore file '/Users/xukong/develop/java/java/MyBookshelf/app/s.keystore.temp' not found for signing config 'myConfig'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

**Comment by xukongyang** [comment]
找到解决方法了，apk成功生成了

signingConfigs {
    release {
        storeFile file("ouman.jks")
        storePassword "com.ouman.car "
        keyAlias "ouman"
        keyPassword "com.ouman.car "
    }
}


buildTypes {
    debug {
        signingConfig signingConfigs.release
    }
    release {
        signingConfig signingConfigs.release
    }
}
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

**是把上面这两段代码全都注释。**

--------------------- 
作者：哆啦U梦 
来源：CSDN 
原文：https://blog.csdn.net/u013952370/article/details/52923353 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by gedoor** [comment]
signingConfig signingConfigs.myConfig
删掉

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: xukongyang<mailto:notifications@github.com>
发送时间: 2018年11月29日 15:55
收件人: gedoor/MyBookshelf<mailto:MyBookshelf@noreply.github.com>
抄送: kunfei<mailto:gekunfei@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [gedoor/MyBookshelf] 不能打开书籍看书！ (#124)


谢谢答复，注释掉上面2行后，编译不报错了，但是在 build apk的时候又报了个错：

Error:FAILURE: Build failed with an exception.

  *   What went wrong:
Execution failed for task ':app:validateSigningDebug'.

Keystore file '/Users/xukong/develop/java/java/MyBookshelf/app/s.keystore.temp' not found for signing config 'myConfig'.

  *   Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
  *   Get more help at https://help.gradle.org

BUILD FAILED in 8s

―
