### ISSUE TITLE
关于4.4停止运行

### ISSUE THREAD

**Issue by 940842546** [gedoor/MyBookshelf#141]
是MultiDex 分包的问题，具体原因是在build.gradle文件中允许了multiDex分包(multiDexEnabled true)，但未在Application初始化的问题。因此只需要在Application中将其初始化即可。
![b65d218a6a625ad0f9244d7e6324653d](https://user-images.githubusercontent.com/8674798/50399028-3a4c4f80-07b7-11e9-8a30-c03bd82e1aa5.jpg)
所以加上这个就行了
@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(base);
    }

就解决4.4打开停止运行的问题了
还有我把firebase删了 应该与firebase不相关 因为删了之后还是停止运行 最后把MultiDex初始化加了就好了

**Comment by gedoor** [comment]
谢谢
