### ISSUE TITLE
疯狂打印日志

### ISSUE THREAD

**Issue by liuwei1225** [gedoor/MyBookshelf#149]
![image](https://user-images.githubusercontent.com/16983459/51182055-e8a36a80-1907-11e9-9ec4-6b42c18fc594.png)
点开阅读页面一直打印这种日志,并且没在应用中搜索到相对应的代码,不知道是否方便告知这块是什么情况导致的,或者告知下日志打印的位置,谢谢:
2019-01-15 20:53:16.208 17080-17579/com.gedoor.monkeybook E/ConfigurationContentLoader: PhenotypeFlag unable to load ContentProvider, using default values

**Comment by gedoor** [comment]
我还特地调试了一下,没有出现这个错误,我搜索了一下ContentProvider,以下是介绍,不过我软件里没有用这个
https://www.jianshu.com/p/f5ec75a9cfea

**Comment by liuwei1225** [comment]
不知道是否是因为firebase相关代码导致的问题,我这边自己创建项目导下来的google_server.json文件,由于firebase以前未接触过,因此没有做其他处理,或许和这块有一定关系.并且项目中会经常出现这两类崩溃,集中体现在书籍切换章节,以及长时间处于后台进入前台的时候,劳烦大神有空的情况下解答下
![image](https://user-images.githubusercontent.com/16983459/51305442-d34c4e80-1a75-11e9-8dfe-0af7d035e851.png)

![image](https://user-images.githubusercontent.com/16983459/51305056-bc592c80-1a74-11e9-934c-9e368f0e3d9c.png)

**Comment by gedoor** [comment]
是注册广播接收报错,这个报错好像是在华为手机上出现,我也不清楚具体原因

**Comment by gedoor** [comment]
if (batInfoReceiver == null) {
            batInfoReceiver = new ThisBatInfoReceiver();
            batInfoReceiver.registerThis();
        }
加个判断看下次还报不报错吧

**Comment by liuwei1225** [comment]
或许真的和手机有关系,用一加测试的,在华为、小米手机上测试暂时未发现这问题,加上这块判断,问题未解决,问题和这代码应该没什么关联,我这边再继续跟进下问题,不过还是多谢解答

**Comment by StevenWT** [comment]
/**
 * The core Android system has died and is going through a runtime restart. All
 * running apps will be promptly killed.
 */
public class DeadSystemException extends DeadObjectException {
    public DeadSystemException() {
        super();
    }
}

两种可能性：
1.系统服务已经死亡，app进程没有被kill
app如果调用系统服务，系统会抛出DeadSystemException，意思是说系统核心服务已经死亡，无法提供服务。
2.系统服务已经死亡，app进程被kill掉
app内存数据丢失，如果app运行依赖内存静态数据，可能会导致app异常。例如空指针错误。


处理方式：
1.被kill掉了可以重新启动应用
2.如果没有被kill掉，调用系统服务出现DeadSystemException。可以考虑暂时不调用当前系统服务，捕捉异常，提示用户系统服务异常，稍后重试。

导致系统崩溃的原因：
firebase 引用了谷歌服务（gms）和7.0系统有冲突（已经发现华为指定7.0系统可以复现）
谷歌服务3毫秒左右会启动一次ConfigurationProvider ,但是每次都启动失败。每次启动失败系统都会抛出一个SecurityException异常
时间长了就把系统搞崩溃了。

启动失败的原因：ConfigurationContentLoader: PhenotypeFlag unable to load ContentProvider, using default values

删除firebase和gms指定系统就不会在复现这个问题

系统日志：
02-01 18:58:04.712 14148 14169 E FA      : Task exception while flushing queue: java.lang.RuntimeException: android.os.DeadSystemException: com.google.android.gms.internal.measurement.zzwu.zzsj(Unknown Source)
02-01 18:58:04.718  1052  2906 W System.err: java.lang.SecurityException: Permission Denial: opening provider com.google.android.gms.phenotype.provider.ConfigurationProvider from ProcessRecord{73c2a 14148:com.debug/u0a7766} (pid=14148, uid=17766) that is not exported from uid 10014
02-01 18:58:04.718  1052  2906 W System.err: 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:11616)
02-01 18:58:04.718  1052  2906 W System.err: 	at com.android.server.am.HwActivityManagerService.getContentProviderImpl(HwActivityManagerService.java:4474)
02-01 18:58:04.718  1052  2906 W System.err: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:12047)
02-01 18:58:04.718  1052  2906 W System.err: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:977)
02-01 18:58:04.718  1052  2906 W System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3171)
02-01 18:58:04.718  1052  2906 W System.err: 	at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:678)
02-01 18:58:04.718  1052  2906 W System.err: 	at android.os.Binder.execTransact(Binder.java:565)
02-01 18:58:04.718 14148 14169 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 172)

**Comment by StevenWT** [comment]
firebase的bug,最新版本修复了，更新firebase版本即可

**Comment by gedoor** [comment]
好的

**Comment by Magicsnail** [comment]
> firebase的bug,最新版本修复了，更新firebase版本即可

请问具体哪个版本号开始修复的？

**Comment by Magicsnail** [comment]
> firebase的bug,最新版本修复了，更新firebase版本即可

firebase修复的版本是哪个呢，我们的版本已经比较新了呀
