### ISSUE TITLE
增加禁止下载封面图的选项

### ISSUE THREAD

**Issue by livelazily** [gedoor/MyBookshelf#150]
能否增加禁止下载封面图的选项?

现在在发现页的排行榜里面随便滚几下就消耗了5~6M的流量, 大部分都消耗在了加载封面图上.

或者考虑在 wifi 下才加载封面图?

**Comment by alhricke** [comment]
我觉得这个是个不错的建议……

**Comment by gedoor** [comment]
现在不都是不限流量的卡了吗?
