### ISSUE TITLE
希望加个选项关闭长按菜单中的 阅读•搜索

### ISSUE THREAD

**Issue by hosxy** [gedoor/MyBookshelf#152]
如图所示，
![photo_2019-01-23_21-25-13](https://user-images.githubusercontent.com/17108640/51610078-c8525c00-1f56-11e9-9833-a134d9527cb4.jpg)
感觉这个菜单并没有什么大用，希望能加个选项关闭这个菜单

**Comment by gedoor** [comment]
已添加开关
