### ISSUE TITLE
[建议]换源时保留缓存

### ISSUE THREAD

**Issue by xxxxst** [gedoor/MyBookshelf#160]
现在换源时会清空缓存，并重新下载所有章节。
但是重新下载速度太慢，特别是对于上千章的小说。
一般换源是因为少部分章节错误，需要重新下载。
**希望换源时增加一个选项，让用户可以保留当前的缓存章节。**
节省下载时间。

之前用的衍墨轩的源，每本书都有十几章下载不了，重新下载又用了一个多小时。。。

**Comment by rainmor** [comment]
好多书源的内容是不一样的！
如果换源之后，原来书源缓存还在，你怎么确定书源变更了？变更还有什么意义？

**Comment by qw4096** [comment]
不同书源的内容拼接在一起是吧。看着简单，其实很多问题的，比如不同书源目录可能会错位，又比如多个书源拼接，更新的时候更新哪个书源的？当然这些可以由用户来选择，但过度增加复杂度不但对app开发不利，对用户也不利

**Comment by xxxxst** [comment]
这个建议是针对少量章节无法下载而言的。
很多app都有这个功能，相信原理上应该是可行的。
具体实现我这里抛砖引玉一下：
目录按照新书源来，通过对比章节名来保留章节，丢失的重新下载
麻烦的地方也就是对比章节名，可以参考一下kdiff3的思路。少部分错位是不会有问题的。

**Comment by gedoor** [comment]
太麻烦
