### ISSUE TITLE
初次使用体验

### ISSUE THREAD

**Issue by swiminger** [gedoor/MyBookshelf#179]
刚才下载试用了一下，字体设置可以选择自己下载的TTF文件，这个+1分，背景可以设置图片颜色，这个+1分，可以上网订阅，这个我不需要，加载下载的epub文件，打开文字编码错误，这个-1分，不能载入mobi文件，这个-1分，语音朗读不能调整速度，不能设置背景音乐，-1分。 希望它能进一步改进。

**Comment by SettingDust** [comment]
[Issue](https://guides.github.com/features/issues/)
