### ISSUE TITLE
我拉下来之后，build gradle一直同步过，是需要是什么设置么

### ISSUE THREAD

**Issue by leonBreeze** [gedoor/MyBookshelf#181]
1、git clone下来之后，报错如下
Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/nullnull/debug/google-services.json
  /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/debug/nullnull/google-services.json
  /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/nullnull/google-services.json
  /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/debug/google-services.json
  /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/nullnullDebug/google-services.json
  /Users/leonbreeze/Desktop/MyBookshelf-master/app/google-services.json

2、添加了google-services.json到 app的目录下
3、build之后出现了
No matching client found for package name 'com.kunfei.bookshelf.debug'

### 是否能提供一个拉下来到运行的步骤说明啥的

**Comment by helloworld10010** [comment]
怎么解决的

**Comment by helloworld10010** [comment]
他在debug闭包里设置了点后缀，把那去掉

**Comment by helloworld10010** [comment]
> 1、git clone下来之后，报错如下
> Error:Execution failed for task ':app:processDebugGoogleServices'.
> 
> > File google-services.json is missing. The Google Services Plugin cannot function without it.
> > Searched Location:
> > /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/nullnull/debug/google-services.json
> > /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/debug/nullnull/google-services.json
> > /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/nullnull/google-services.json
> > /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/debug/google-services.json
> > /Users/leonbreeze/Desktop/MyBookshelf-master/app/src/nullnullDebug/google-services.json
> > /Users/leonbreeze/Desktop/MyBookshelf-master/app/google-services.json
> 
> 2、添加了google-services.json到 app的目录下
> 3、build之后出现了
> No matching client found for package name 'com.kunfei.bookshelf.debug'
> 
> ### 是否能提供一个拉下来到运行的步骤说明啥的

他在debug闭包里设置了点后缀，把那去掉
