### ISSUE TITLE
正则替换规则中的引用问题

### ISSUE THREAD

**Issue by lon91ong** [gedoor/MyBookshelf#182]
比如文章有`'国'军，'国民'党`字样，我想要把单引号去掉
在EmEditor等支持正则替换的编辑器中，查找\’(.{1,4})\‘，替换为\1
在阅读中试了，似乎没有\1这样引用的方式

请大侠赐教

**Comment by Antecer** [comment]
标准的正则表达式规范你应该使用的是 $1

**Comment by lon91ong** [comment]
@Antecer 原来如此，受教了
