### ISSUE TITLE
提个需求

### ISSUE THREAD

**Issue by hnzyc** [gedoor/MyBookshelf#186]
我也提个需求，可否增加微信公众号的阅读功能，也就是把公众号的文章打包成书籍，谢谢

**Comment by Debatrix** [comment]
这个需求比较困难吧 毕竟目前微信订阅号没有开放接口 app很难自行抓取打包 不如考虑瓦斯+rss之类的方案

**Comment by gedoor** [comment]
这个暂不考虑
