### ISSUE TITLE
离线章节的Bug

### ISSUE THREAD

**Issue by yilianxin** [gedoor/MyBookshelf#192]
我看的某本书有10000多章,现在发现离线章节的文本框应该最大限度是9999(应该是),那么后继章节就无法离线保存了.希望修改一下

**Comment by gedoor** [comment]
可以继续输入,可能显示不下,可以输入更大的数字

**Comment by yilianxin** [comment]
不能输入，会提示输入错误
比如现在是5000章，要下到12345，现在显示1234，5应该没输入上去

**Comment by gedoor** [comment]
好的,我看一下
