### ISSUE TITLE
需求请求：希望可以选择关闭段首缩进

### ISSUE THREAD

**Issue by RunningMelos** [gedoor/MyBookshelf#193]
在电子设备上阅读，有些会选择此排版方案（例如大部分微信公众文章）。通过**段首无缩进，段间距拉宽**，使用过程中可以部分降低阅读疲劳感。
曾尝试用正则去掉段首缩进无效，希望能考虑一下在软件层面变成**可选项**，谢谢啦。

**Comment by gedoor** [comment]
好的
