### ISSUE TITLE
提个需求：能够直接备份到/恢复从 gist

### ISSUE THREAD

**Issue by alexya** [gedoor/MyBookshelf#196]
现在的备份和恢复可以保留，可否提供更方便的备份和恢复。
比如，通过github的gist。我记得我在使用vscode的syncsetting也用到过，可以 把vscode的所有设置直接upload到gist上面，换机器了，再download下来，很快速方便。
不知道该app也可以类似这样？毕竟，移动互联网时代，备份到本地磁盘，拷贝出来，换机器，安装app，拷贝进去，再恢复，实在是有点儿...... 
（我说提备份恢复是 app里关注的书籍和已经阅读的index，可不是书籍全文）

当然这个功能属于高级功能，一般用户可能也不太会用。但对于会用的人来说，非常方便了。

**Comment by SettingDust** [comment]
webdev

**Comment by alexya** [comment]
@SettingDust 现在有webdav这个功能么？没有看到啊......刚才特意打开app看了一下。只能备份到磁盘/文件夹的功能。

**Comment by SettingDust** [comment]
星际选手?

**Comment by gedoor** [comment]
用webdav吧,设置里
