### ISSUE TITLE
黑色背景下文字重影

### ISSUE THREAD

**Issue by WeijieH** [gedoor/MyBookshelf#203]
如图:
目前只发现黑色背景下才会有重影. 软件版本是最新的2.19.032119. 之前的版本也有一样的问题.
手机是三星S9+, 系统是Android 9.
![image](https://user-images.githubusercontent.com/16510655/54793947-6f800680-4c1b-11e9-9369-3347b7823cb2.png)

**Comment by Antecer** [comment]
仔细看这个重影应该是下一页的内容...

**Comment by WeijieH** [comment]
重影其实是前页的内容. 在我这里重复步骤是这样的:
点开任意书籍后, 设置黑色背景, 向前翻一页或者2页后, 背景出现前页文字的留影.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16510655/55081852-f5b2a780-5076-11e9-9797-20cb57165d6d.gif)
颜色设置都是默认没有更改, 截图在下面:
![SmartSelect_20190327-100005](https://user-images.githubusercontent.com/16510655/55084409-868b8200-507b-11e9-8f6e-bd6ccc8a032e.jpg)
![SmartSelect_20190327-100020](https://user-images.githubusercontent.com/16510655/55084410-868b8200-507b-11e9-8bcb-0371407ce80e.jpg)

**Comment by gedoor** [comment]
你选的背景好像有透明度,清空下数据重新选背景试试
