### ISSUE TITLE
指定规则的是否把书院url当做基础url？？

### ISSUE THREAD

**Issue by lukemin** [gedoor/MyBookshelf#208]
指定规则的是否把书源url当做基础url？？
如书源url为http://111.com
发现规则里面的就不要出现::http://111.com/分类1 ::http://111.com/ 分类2
而变成 通用规则 ::booksourceUrl/分类1  ::booksourceUrl/分类2
搜索也是booksourceUrl/search.php 
当然如果不同也可以填写其他网址
但大多为网址应该是一样的
这样当书源网址变化只需要修改一下书源url就可以了，而不用写过其他规则，尤其是在手机上修改有点麻烦。

**Comment by gedoor** [comment]
发现规则可以省略baseUrl

**Comment by lukemin** [comment]
怎么写？

**Comment by gedoor** [comment]
发现规则直接省略host之前的,已/开头

**Comment by lukemin** [comment]
6666，谢谢！

**Comment by gedoor** [comment]
好像有点问题,下个版本支持
