### ISSUE TITLE
翻页模式：滚动时的翻页速度太慢了

### ISSUE THREAD

**Issue by atiAkizuki** [gedoor/MyBookshelf#213]
自我感觉翻页模式：滚动时翻页速度太慢了，手指划完整个屏幕才向下滚动5-6行。
个人感觉翻页动画应该是手指按压下的行，紧随划动的手指滚动才比较自然。常见的app都是这样的效果。如酷安的评论区、知乎和静读天下的翻页动画：无。

**Comment by gedoor** [comment]
现在就是跟随手指啊,

**Comment by atiAkizuki** [comment]
仔细观察了一下，在手指快速滑动时，很明显有滚动速度跟不上手指划动的情况。与此同时，静读天下的动画效果与其他常用app（如酷安评论区，知乎等）的动画效果一致。
我录了MP4，可以看下动画效果的不同。
静读天下[https://streamable.com/65ntw](https://streamable.com/65ntw)
阅读[https://streamable.com/7ey4k](https://streamable.com/7ey4k)
酷安[https://streamable.com/zrjmb](https://streamable.com/zrjmb)
