### ISSUE TITLE
提几点建议

### ISSUE THREAD

**Issue by zhaohuiyingxue** [gedoor/MyBookshelf#22]
1、搜索页面的排序，应当按书名、作者名排序。
2、还是搜索页面，对书名、作者名能否做一下优化，主要是空格，比如以下几种会认为是不同的书，实际上是空格在作怪，希望能特殊处理一下。我目前是增加了正则替换（[ ]|[\&nbsp;][全文阅读]以及.*：），但我认为，既然这两个字段是作为唯一标识，应当在程序中处理好。
修真聊天群（圣骑士的传说）
修真聊天群  （圣骑士的传说）
修真聊天群  （  圣骑士的传说）
修真聊天群  （作 者圣骑士的传说）
修真聊天群  （作&nbsp;&nbsp;者圣骑士的传说）
3、换源时候可以根据更新日期进行排序？这样比较方便找到更新快的网站。
4、小说目录时候可以倒序排列？

**Comment by zhaohuiyingxue** [comment]
PS，能不能支持API？比如追书的API，以及其他网站的API，返回的数据都是json格式的。

**Comment by gedoor** [comment]
API需要写JAVA,目前内置了一个
