### ISSUE TITLE
编译错误希望解决一下谢谢

### ISSUE THREAD

**Issue by M17764017422** [gedoor/MyBookshelf#3]
File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
C:\Users\aide\Documents\MyBookshelf\app\src\nullnull\debug\google-services.json
C:\Users\aide\Documents\MyBookshelf\app\src\debug\nullnull\google-services.json
C:\Users\aide\Documents\MyBookshelf\app\src\nullnull\google-services.json
C:\Users\aide\Documents\MyBookshelf\app\src\debug\google-services.json
C:\Users\aide\Documents\MyBookshelf\app\src\nullnullDebug\google-services.json
C:\Users\aide\Documents\MyBookshelf\app\google-services.json

**Comment by gedoor** [comment]
把

**Comment by nobk** [comment]
我也遇到这个问题，没这方面的经验。@gedoor 请解释一下编译方法吧。
我搜索的结果是需要去Firebase console下载一份google-services.json，但还是不知道package_name应该怎么填，我填写成com.gedoor.monkeybook或者com.kunfei.bookshelf，编译都报错：No matching client found for package name 'com.gedoor.monkeybook.debug'

**Comment by shutaozhenzhen** [comment]
https://github.com/gedoor/MyBookshelf/issues/314

**Comment by dashu3344** [comment]
> File google-services.json is missing. The Google Services Plugin cannot function without it.
> Searched Location:
> C:\Users\aide\Documents\MyBookshelf\app\src\nullnull\debug\google-services.json
> C:\Users\aide\Documents\MyBookshelf\app\src\debug\nullnull\google-services.json
> C:\Users\aide\Documents\MyBookshelf\app\src\nullnull\google-services.json
> C:\Users\aide\Documents\MyBookshelf\app\src\debug\google-services.json
> C:\Users\aide\Documents\MyBookshelf\app\src\nullnullDebug\google-services.json
> C:\Users\aide\Documents\MyBookshelf\app\google-services.json

你解决这个问题了吗
