### ISSUE TITLE
现在无法下载了吗

### ISSUE THREAD

**Issue by LiJie008** [gedoor/MyBookshelf#309]

**Comment by gedoor** [comment]
可以啊

**Comment by LiJie008** [comment]
不是说源规则改变，现在无法获取绝大部分的小说，所以关闭了吗???

**Comment by gedoor** [comment]
你是指无法下载什么,现在可以正常使用啊

**Comment by LiJie008** [comment]
https://www.hostfans.cn/  此网站的通知栏上说“由于追书神器的源规则改变，现在无法获取绝大部分的小说，所以暂时关闭了”。唔，我还没下载此软件呢，看到这个通知以为现在不能用了

**Comment by gedoor** [comment]
其它书源正常使用,止软件不依赖716

**Comment by HoterCyc** [comment]
5月开始，716的就开始不能正常使用了！

**Comment by gedoor** [comment]
最新版修复了一些BUG
