### ISSUE TITLE
无论怎么修改包名都不行

### ISSUE THREAD

**Issue by wanmeiwl** [gedoor/MyBookshelf#34]
No matching client found for package name 'com.gedoor.monkeybook.debug'

**Comment by gedoor** [comment]
修改包名干什么

**Comment by wanmeiwl** [comment]
OK  和包名无关  在 buildconfig.java 里有：
`public static final String APPLICATION_ID = "com.gedoor.monkeybook.debug";`
然后，MAKE PROJECT时，提示：
`No matching client found for package name 'com.gedoor.monkeybook.debug'`
这是为什么？是因为目前开启了 debug 但是不存在com.gedoor.monkeybook.debug这个类？

新人  求带
