### ISSUE TITLE
[替换净化]去除开头的问号

### ISSUE THREAD

**Issue by Azureki** [gedoor/MyBookshelf#349]
正则应该是`^\\?`或者`^\?`吧？可是试了都没有用。
~是不支持`^`吗？~
去掉`^`，使用`\?`就可以了。
不过这样中间的也没了。我还是想只去掉开头的，应该怎么做呢？

**Comment by lon91ong** [comment]
试试`(^\W*)?\?`

**Comment by Azureki** [comment]
@lon91ong 加了 `^` 的正则表达式都没用。
