### ISSUE TITLE
在使用阅读过程中，遇到一些问题

### ISSUE THREAD

**Issue by agutools** [gedoor/MyBookshelf#361]
在使用 “阅读”过程中，遇到一些问题或建议： 

1、问题：在TTS朗读过程中，如果程序被终止，重新打开后定位在上一次打开的位置（不能记录阅读进度）；后台切前台也有机率出现同样的问题；

2、问题：在语音阅读过程中，如果发生屏幕旋转，阅读就会终止； 

3、问题：语音阅读章节标题的时候，有机率会出现重复前两个字的问题（第X第X…章）； 

4、问题：净化规则“土着”替换“土著”无效，但其它规则却正常工作；已找到问题所在：是开启繁简转换功能所引起的问题 。

5、问题：在滚动翻页模式中点击翻页，会出现不能完整翻页的问题；

6、问题：网络导入净化规则，会清空自定义规则；

7、建议：能否添加当前页面所生效的净化规则统计/提示呢？ 

8、问题：不能正确语音阅读百分数（旧版阅读星也不能正确阅读百分数和小数，经反馈并更新之后能正常阅读，Tts同是讯飞语音） 

9、问题：净化规则正则符号“^”（行首）无效 ；“$”（行尾）也有同样的问题；

10、问题：语音阅读到下一页内容（跨页行），却不会跟随自动翻页；

11、建议：能否指定扫描目录，自动分组添加所有子文件夹下的TXT，现在只能一个个文件夹手动全选添加；

12、建议：“智能导入”中无关的TXT太多，也不方便添加，要是能加入文件大小筛选就更方便了；

13、建议：“所有书籍”能添加自定义分组目录功能，如：科幻、武侠、军事……等；

14、问题：从TTS朗读状态退出后，再次点击语音阅读按钮，很大几率不能开始朗读，必须返回“所有书籍”重新打开书本后才能TTS阅读；

15、建议：添加手动指定TTS引擎的功能（在一台手机(YunOS)上内置有TTS，另外安装了讯飞语记后，因为系统没提供默认语音引擎的设置，结果阅读还是使用内置那个语音怪怪的默认引擎）

16、问题：离线下载 任务中断没提示，中断后“下载任务”任务消失，建议加入中断自动重试次数、中断提示、“下载任务”页面保留完成/未完成任务管理，将离线内容从设置→清理缓存中独立出来；

**Comment by agutools** [comment]
第4点，发现是应用程序默认将“著”替换为“着”，源文件中是正确“著”——为什么！？

**Comment by gedoor** [comment]
你可能开了繁转简

**Comment by agutools** [comment]
◆ 能否指定扫描目录，自动分组添加所有子文件夹下的TXT，现在只能一个个文件夹手动全选添加；
◆ “智能导入”中无关的TXT太多，也不方便添加，要是能加入文件大小筛选就更方便了
◆ 希望“所有书籍”能加入分组目录功能，如：科幻、武侠、军事……等
