### ISSUE TITLE
建议：增加书友社区、书单等功能

### ISSUE THREAD

**Issue by allblue** [gedoor/MyBookshelf#393]
目前app阅读小说体验满分，但是书荒找书能力有点弱，发现的效率太低，建议增加这方面功能。比如：
1. 书评：可对整体小说或单章进行评价，根据评价内容可快速筛选目标书籍
2. 书单：或者可以集成优书网这种专门的书单网站
3. 同类小说推荐：可在书籍详情页中推荐同类型小说
4. 书友社区：自由讨论、书荒求书推书等

**Comment by mutouhk** [comment]
需要用到服务器~ 所以不会进行这个功能的开发

**Comment by allblue** [comment]
希望未来条件允许的时候，可以考虑增加下
