### ISSUE TITLE
建议添加滚动阅读

### ISSUE THREAD

**Issue by libingChina** [gedoor/MyBookshelf#396]
一直在uc看小说,习惯了上下滑动,建议可以添加进去

**Comment by mutouhk** [comment]
有滚动~  在阅读小说正文的界面上   点击屏幕中间  会出来菜单

有个  “界面” 的设置按钮~

**Comment by you-hengh** [comment]
> 一直在uc看小说,习惯了上下滑动,建议可以添加进去

是的,我本来也打算反馈这个问题,看到作者回复找到了地方 ,
其实这个功能还是放在容易识别地方  单单一个覆盖的提示 让人很难联想到是设置翻页方式的
附图
![图片](https://s2.ax1x.com/2019/10/24/KNE35t.jpg)

**Comment by libingChina** [comment]
> 有滚动〜在阅读小说正文的界面上点击屏幕中间会出来菜单
> 
> 有个“界面”的设置按钮〜

好的谢谢回复,找到功能了,菜单显示覆盖很让人误解
