### ISSUE TITLE
建议批量导入书源功能

### ISSUE THREAD

**Issue by libingChina** [gedoor/MyBookshelf#397]
就是书源网站可以弄成多个书源打包一起导入,比如多个书源打包成一个文件以特定分隔符分隔,或者约定一个api接口,网站可以根据用户自定义书源打包,用户直接一键导入,顺便说一下书源二维码导入考虑换成api接口这种,(书源规则二维码实在太大了,手机半天都扫出不来),还可能就是用户自定义书源规则,直接自动在书源网站提取书源

**Comment by mutouhk** [comment]
书源网站和作者无关~~  书源网站都是书友自主建立分享的~

**Comment by libingChina** [comment]
> 书源网站和作者无关~~书源网站都是书友自主建立分享的〜

我的意思是约定一个api接口,可以批量导入,感觉一个一个导入太麻烦了

**Comment by mutouhk** [comment]
比如源仓库的 WEB导入？

**Comment by libingChina** [comment]
> 比如源仓库的 WEB导入？

谢谢回复,刚刚使用研究不深,导致很多功能实在找不到,打扰了,web服务能实现
