### ISSUE TITLE
请问为什么这条替换规则不生效

### ISSUE THREAD

**Issue by agutools** [gedoor/MyBookshelf#400]
请问为什么这条替换规则不生效：

名称：修正断句
规则：(?<![。！？…—：；～〗】》\.\?\!\"\]\}\)\:\;）”章节文])$\s+
替换：

——是哪里错了吗？
PS：去掉"$"就有效，但规则变得不精确；可是这规则在其他文本编辑器中测试有效

**Comment by Celeter** [comment]
没开启多行模式
