### ISSUE TITLE
E-ink模式翻页还是有动画

### ISSUE THREAD

**Issue by liansishen** [gedoor/MyBookshelf#407]
设备海信A5，开启E-ink模式
阅读页面翻页任然有翻页动画。

**Comment by withtea** [comment]
确实是这样 可以将“开启E-ink模式” 改为 单独 “关闭翻页动画”

**Comment by withtea** [comment]
“开启E-ink模式”  可以另外定义成背景FFFFFF 字体000000 局部刷新
