### ISSUE TITLE
部分代码文件丢失，无法正确编译

### ISSUE THREAD

**Issue by ijkzen** [gedoor/MyBookshelf#411]
![批注 2019-11-15 173346](https://user-images.githubusercontent.com/31531836/68932709-209c6800-07ce-11ea-957d-8ba70f0fc970.png)
我是想加一个小功能，但是代码文件似乎不全

**Comment by gedoor** [comment]
这些自动生成的

**Comment by ijkzen** [comment]
好的，我再试试

**Comment by shutaozhenzhen** [comment]
https://github.com/gedoor/MyBookshelf/issues/314
试试？

**Comment by ijkzen** [comment]
> 
> 
> #314
> 试试？

@shutaozhenzhen 这个问题已经解决了，感谢您的关心。
