### ISSUE TITLE
[Feature Request] 增加语音朗读时，音量为0，自动暂停功能

### ISSUE THREAD

**Issue by lowwor** [gedoor/MyBookshelf#433]
希望增加语音朗读时，音量为0，自动暂停功能

**Comment by M17764017422** [comment]
自动暂停的条件是什么？目前已经有定时朗读功能了

**Comment by lowwor** [comment]
自动暂停的条件是当一直按实体音量键减音量到零的时候，可以自动暂停朗读。
使用场景是，一般开始语音朗读后，手机会息屏来听，这时候出现突发情况，比较快的方式是一直按着音量键让他静音，而不是再解锁手机暂停。这个情况下希望语音朗读可以暂停，进度不会自动往前走。

**Comment by nobk** [comment]
你不用解锁啊，给阅读权限，就能显示在锁屏界面上，暂停、停止和定时的按钮都有显示。
按一下电源键亮屏再点一下暂停，不比你关掉音量还得重新打开方便些吗。
戴蓝牙耳机听的时候，点一下蓝牙耳机的接听键也能暂停。

**Comment by lowwor** [comment]
其实是睡觉的时候，困了的话，连屏幕都不想亮，亮了就醒了，直接按音量键到零，暂停睡觉。

**Comment by nobk** [comment]
睡觉还是提前设置定时停止管用，否则睡着了不知道按暂停一直读影响睡眠质量。

**Comment by lowwor** [comment]
好的，谢谢，那只能自己改一个来用了。
