### ISSUE TITLE
开启 E-lnk 模式仍无法关闭翻页动画

### ISSUE THREAD

**Issue by lwsgh** [gedoor/MyBookshelf#451]
1. 在主题设置中开启 E-lnk 模式后, 仍然有翻页动画
2. 是否可以添加在 E-lnk 模式时关闭所有动画效果

**Comment by gedoor** [comment]
翻页动画单独设置

**Comment by micsem00** [comment]
@gedoor 翻页动画怎么进行单独设置？

**Comment by gedoor** [comment]
界面设置里

**Comment by 1298882690** [comment]
进入一本书，点击页面中间，在弹出的界面选项里，默认是覆盖好像

**Comment by micsem00** [comment]
@gedoor @1298882690 收到，谢谢

**Comment by Hermit10** [comment]
> 进入一本书，点击页面中间，在弹出的界面选项里，默认是覆盖好像

感谢好人，找了好久！
