### ISSUE TITLE
E-INK模式没有关闭翻页动画

### ISSUE THREAD

**Issue by flijun** [gedoor/MyBookshelf#469]
电纸书使用，如何关闭翻页动画？电纸书刷新太卡了。E-INK模式依然有动画。
另外界面选择中白底黑字貌似对比度不够，不是纯白色的底色，对墨水屏更不友好了

**Comment by Celeter** [comment]
翻页可以选无动画

**Comment by flijun** [comment]
已经解决，谢谢
