### ISSUE TITLE
本地txt断章有误

### ISSUE THREAD

**Issue by eric0815** [gedoor/MyBookshelf#47]
有时候txt的章节末尾会带上下一章的标题的前几个字,比如下面网址的txt文件,本地导入后,第58章以后的每一章的末尾都有问题

http://m.jjxsw.com/txt/dl-10-29712.html
如图:
![image](https://user-images.githubusercontent.com/1378812/45991125-011c1a80-c0b6-11e8-80e3-06a49c0d76bc.png)

**Comment by eric0815** [comment]
发现原因是判断文本文件编码导致的这个问题,这个txt文件,源码中使用的UniversalDetector编码判断结果是gb18030就会出现问题,使用头三个字符来判断结果是GBK,就不会有这个问题,大概是txt中出现了GBK编码之外的字符?

**Comment by gedoor** [comment]
没找到原因
