### ISSUE TITLE
web服务打开后无法关闭

### ISSUE THREAD

**Issue by shishirong** [gedoor/MyBookshelf#472]
BUG：
1. web服务打开后无法关闭.
2. 安装新版本时不是替换掉旧版软件，而是新安装了一个APP.
3. #462 提到的 “epub书不显示封面图片和正文图片、跳转链接不能跳转” 的问题仍未解决.

**Comment by Celeter** [comment]
1.去看通知栏
2.阅读2.0和3.0是两个不同应用
3.阅读2.0不支持图片和链接

**Comment by shishirong** [comment]
@Celeter 更新之后现在通知栏有取消按钮了。请问阅读3.0在哪儿下载？

**Comment by Celeter** [comment]
@世世荣 阅读3.0下载：https://github.com/gedoor/legado/releases
