### ISSUE TITLE
解析问题

### ISSUE THREAD

**Issue by buzai** [gedoor/MyBookshelf#505]
class.s2@tag.a@text
这种是什么解析
xpath好像不是这样的啊

**Comment by gedoor** [comment]
这个自定义的规则,xpath也支持的,

**Comment by buzai** [comment]
@gedoor 我看代码最后是将这个定义为 default model ，而不是 xpath模型，能简单说下这个default解析格式的思路么

**Comment by gedoor** [comment]
看书源规则,自定义的规则比较简单
http://www.legado.top/MyBookshelf/sourcerule.html
