### ISSUE TITLE
博阅 Likebook Mars 电子书下闪退

### ISSUE THREAD

**Issue by yefoenix** [gedoor/MyBookshelf#71]
打开APP后直接提示停止运行。
Android 版本 6.0.1, 系统固件版本 BYRead-V1.0.2-2018092813.

另外问一下，报错的日志如何获取？

**Comment by bylevel** [comment]
我在博阅 Likebook Mars上也出错，用adb logcat 导出日志

```
10-09 21:26:30.779 E/DisplaydConnector(  546): Communications error: java.io.IOException: No such file or directory
10-09 21:26:30.779 E/DisplaydConnector(  546): Error in NativeDaemonConnector: java.io.IOException: No such file or directory
```

提示 io 错误。

**Comment by gedoor** [comment]
自定义下缓存路径试试吧

**Comment by bylevel** [comment]
错误提示里面出现了`Failed to find provider info for com.google.android.gms.phenotype` 和 `Unable to launch app com.google.android.gms/10005 for service Intent`。

我去掉 firebase 和 gms 引入后就正常了。

**Comment by gedoor** [comment]
自己去掉google统计组件编译吧
