### ISSUE TITLE
关于分页

### ISSUE THREAD

**Issue by atbest** [gedoor/MyBookshelf#79]
现在的分页是先计算好每一页的内容，存在一个TxtPage里面，然后退出阅读界面时保存当前的页码，这样如果在另外一本书里面更改了版面设置，比如页边距、行距、段距、字号等使每一页的内容发生变化后，再按照原来保存的页码打开就会错页，所以我认为应该保存的是从文章开头到当前页码第一行的总字符数，这样无论版面设置怎么改变，都可以根据总字符数计算出正确的页码。

为了方便这种计算，我觉得应该要把TxtPage换成TxtLine，记录每一行的信息，包括内容、Paint的横坐标、纵坐标相对于上一行的偏移量、是否是标题、字数，然后在PageLoader里面读取出来以后按照顺序存到一个数组列表里面，同时用一个列表记录每一页的行数，这样跟原来的方法相比性能上应该没有很大问题。而且因为记录了每一行的行高和位置，因此也比较容易根据位置判断对应的行数和内容，便于实现长按复制搜索等功能。

还有一个好处，利用这种方法在滚动模式下根据滚动的偏移量，可以很容易的计算出页首和页尾的行号，再进行drawText，应该可以解决出现在页尾的多余空白，就是不知道这样实时地写字性能如何，或许可以限制一下滚动速度，或者多画几行在没有新行出现的时候只是上下平移一下。而且，因为行数能确定下来，在朗读的时候就能够确定页面上显示的内容是啥，从而不再出现乱页的问题。

抛砖引玉一下，不知道这样是否可行？

**Comment by gedoor** [comment]
可以在动画结束时再写入页码,这样就不会出现滚动时不停写入页码

**Comment by gedoor** [comment]
纯黑的主题没有层次感,我后面准备添加多主题,到时再添加纯黑主题吧,夜间模式就不用纯黑的了

**Comment by atbest** [comment]
是的，在onFling的时候再写页码就可以了。还有动作检测是不是应该换成 GestureDetector ，这样比较容易区分短按还是长按，参考一下 https://github.com/bifan-wei/HwTxtReader ，应该还是可以实现直接长按复制搜索之类的，而不用菜单里面的拷贝内容。
