### ISSUE TITLE
建议：对于已有缓存章节的源增加高亮或者其它标记区别

### ISSUE THREAD

**Issue by RookieApe** [gedoor/MyBookshelf#8]
有时候，在某个源缓存了整本书。但是由于章节缺失，切换到其它源看完缺失的章节，想回到原来已缓存的源看，但是忘了是哪个源。
因此，希望增加特征区分缓存了章节的源与没有缓存章节的源

**Comment by atbest** [comment]
https://github.com/gedoor/MyBookshelf/pull/32 应该修复这个问题了。

**Comment by atbest** [comment]
https://github.com/gedoor/MyBookshelf/pull/38 可以按照换源的顺序排序。
https://github.com/gedoor/MyBookshelf/pull/40 在阅读界面换源时不删除缓存，其他地方换源时删缓存。
